image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: CodecovExample.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test /p:DebugType=full --logger:trx;LogFileName=results.trx /p:DebugType=full CodecovExample.Tests.fsproj" -filter:"+[CodecovExample.TargetProject]* -[CodecovExample.Tests]*" -output:MyProject_coverage.xml -oldstyle
- codecov -f "MyProject_coverage.xml